name: Build release binaries

on:
  push:
    branches: [ main, master ]
  pull_request:
    paths-ignore:
            -'Readme.md'

permissions:
  contents: read

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Build release
        run: cargo build --release

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: SystemMonitor-${{ matrix.os }}
          path: target/release/SystemMonitor

  build-debian:
    runs-on: ubuntu-latest
    container: debian:stable

    steps:
      - name: Install dependencies
        run: apt-get update && apt-get install -y curl build-essential git ca-certificates

      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Build release
        run: cargo build --release

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: SystemMonitor-debian
          path: target/release/SystemMonitor
