name: Build release binaries

on:
  push:
    branches: [ main, master ]
  pull_request:
    paths-ignore:
            -'README.md'

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          profile: minimal

      - name: Build release
        run: cargo build --release

      - name: Upload binary artifact
        uses: actions/upload-artifact@v4
        with:
          name: SystemMonitor-${{ matrix.os }}
          path: target/release/SystemMonitor
